import type { LegalDoc } from "./types";
import { LEGAL_CONTACT_EMAIL } from "@/lib/legal-version";

export const privacyDoc: LegalDoc = {
  title: "Privacy Policy",
  intro: (
    <p>
      This Privacy Policy describes how Marketa ("we", "us", "our") collects, uses, discloses, and
      safeguards your personal information. Marketa is committed to protecting your privacy in
      accordance with the Philippine Data Privacy Act of 2012 (Republic Act No. 10173), its
      Implementing Rules and Regulations, and applicable issuances of the National Privacy
      Commission.
    </p>
  ),
  sections: [
    {
      id: "collected",
      title: "1. Information We Collect",
      body: (
        <p>
          We collect information you provide directly (registration, KYC, listings, messages),
          information generated by your use of the Service (device, log, and behavioral data), and
          information from third parties strictly necessary to verify your identity.
        </p>
      ),
    },
    {
      id: "personal",
      title: "2. Personal Information",
      body: (
        <p>
          Includes name, email address, contact details, profile photo, and general location. This
          information is used to operate your account and enable interactions with other users.
        </p>
      ),
    },
    {
      id: "kyc",
      title: "3. Identity Verification Data",
      body: (
        <p>
          Includes photographs of your government-issued Philippine National ID, extracted OCR
          fields, liveness video and captured frames, and verification results. This data is used
          solely to confirm your identity and prevent fraud.
        </p>
      ),
    },
    {
      id: "device",
      title: "4. Device Information",
      body: (
        <p>
          Includes device type, browser, operating system, IP address, and technical logs necessary
          for the security, availability, and troubleshooting of the Service.
        </p>
      ),
    },
    {
      id: "auth",
      title: "5. Authentication Data",
      body: (
        <p>
          Includes hashed passwords, hashed MPINs, email verification codes, session tokens, and
          reauthentication tokens. Passwords and MPINs are never stored in plain text.
        </p>
      ),
    },
    {
      id: "transactions",
      title: "6. Transaction Information",
      body: (
        <p>
          Includes listings you post, transactions you propose or complete, ratings, reviews, and
          appeal submissions. This information supports the marketplace and trust-score system.
        </p>
      ),
    },
    {
      id: "messaging",
      title: "7. Messaging Data",
      body: (
        <p>
          Includes messages you send through in-app chat, attached media, edits, and message
          metadata. Chat content is visible only to the participants of a thread; administrators
          may access chats only with dual-consent when an appeal is under review.
        </p>
      ),
    },
    {
      id: "audit",
      title: "8. Audit Logs",
      body: (
        <p>
          We maintain tamper-resistant, hash-chained audit logs of security-relevant events
          (authentication, KYC actions, moderation decisions, administrative changes). Logs contain
          the minimum data necessary for accountability and forensic review.
        </p>
      ),
    },
    {
      id: "behavior",
      title: "9. Behavioral Monitoring Data",
      body: (
        <p>
          We record signals such as login attempt frequency, MPIN failures, listing/messaging
          bursts, and cancellation patterns to detect abuse. This data feeds a rule-based risk
          score used only to protect the community.
        </p>
      ),
    },
    {
      id: "purpose",
      title: "10. Purpose of Data Collection",
      body: (
        <ul className="list-disc pl-6 space-y-1">
          <li>To provide, operate, and improve the Service.</li>
          <li>To verify identity and prevent fraud.</li>
          <li>To enable communication and transactions between users.</li>
          <li>To enforce our Terms and Community Guidelines.</li>
          <li>To comply with legal obligations.</li>
        </ul>
      ),
    },
    {
      id: "storage",
      title: "11. Data Storage",
      body: (
        <p>
          Personal data is stored on secure managed infrastructure operated by our processors, with
          restricted network access, encryption in transit, and encryption at rest for sensitive
          artifacts. Data centers used by our processors comply with international security
          standards.
        </p>
      ),
    },
    {
      id: "retention",
      title: "12. Data Retention",
      body: (
        <p>
          We retain personal data only for as long as necessary to fulfill the purposes for which
          it was collected, or as required by law. On account deletion, personal identifiers and
          KYC media are erased after a 30-day grace period, while limited anonymized records may
          be retained for legal and accounting purposes.
        </p>
      ),
    },
    {
      id: "security",
      title: "13. Data Security",
      body: (
        <p>
          We employ administrative, technical, and physical safeguards including access controls,
          row-level security, hashed credentials, monitoring, and audit logging to protect your
          personal information against unauthorized access, alteration, or disclosure.
        </p>
      ),
    },
    {
      id: "encryption",
      title: "14. Encryption",
      body: (
        <p>
          Communications between your device and Marketa are protected by TLS. Passwords and MPINs
          are stored as one-way cryptographic hashes. Audit log entries are chained using SHA-256
          for tamper evidence.
        </p>
      ),
    },
    {
      id: "rights",
      title: "15. Your Rights",
      body: (
        <p>
          Under RA 10173 you have the right to be informed, to object, to access, to correct,
          to erasure or blocking, to damages, to data portability, and to file a complaint. To
          exercise these rights, contact us at{" "}
          <a className="text-primary underline" href={`mailto:${LEGAL_CONTACT_EMAIL}`}>
            {LEGAL_CONTACT_EMAIL}
          </a>
          .
        </p>
      ),
    },
    {
      id: "sharing",
      title: "16. Data Sharing",
      body: (
        <p>
          We do not sell your personal information. We share data only with (a) service providers
          acting on our behalf under confidentiality obligations, (b) government authorities when
          legally required, or (c) other users to the limited extent necessary to complete a
          transaction (e.g., display name, ratings).
        </p>
      ),
    },
    {
      id: "third-parties",
      title: "17. Third-Party Services",
      body: (
        <p>
          We use trusted processors for hosting, database, storage, email delivery, and identity
          document analysis. Each processor is bound by contractual privacy and security
          obligations.
        </p>
      ),
    },
    {
      id: "cookies",
      title: "18. Cookies and Local Storage",
      body: (
        <p>
          We use browser storage for authentication sessions, MPIN unlock state within a session,
          and interface preferences. We do not use third-party advertising cookies.
        </p>
      ),
    },
    {
      id: "contact",
      title: "19. Contact Information",
      body: (
        <p>
          For privacy inquiries, corrections, or complaints, contact our Data Protection Officer
          at{" "}
          <a className="text-primary underline" href={`mailto:${LEGAL_CONTACT_EMAIL}`}>
            {LEGAL_CONTACT_EMAIL}
          </a>
          . You may also file a complaint with the National Privacy Commission of the Philippines.
        </p>
      ),
    },
  ],
};
