// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://gsawquzxlrkraylbyitt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzYXdxdXp4bHJrcmF5bGJ5aXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2ODYzOTIsImV4cCI6MjA5MjI2MjM5Mn0.awgPGJQFZLUwDUQeqtPeFfQKtD4NxuQdAhtKFS8w1ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});